# Generated by Django 4.2.13 on 2026-07-04 19:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0011_rating_survey_anon_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyhashlink',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='زمان انقضا'),
        ),
        migrations.AddField(
            model_name='surveyhashlink',
            name='expiry_unit',
            field=models.CharField(blank=True, choices=[('hours', 'ساعت'), ('days', 'روز'), ('weeks', 'هفته')], max_length=10, null=True, verbose_name='واحد انقضا'),
        ),
        migrations.AddField(
            model_name='surveyhashlink',
            name='expiry_value',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='مقدار انقضا'),
        ),
        migrations.AddField(
            model_name='surveyhashlink',
            name='max_participants',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='حداکثر تعداد شرکت\u200cکنندگان'),
        ),
    ]
