# Generated by Django 5.2.16 on 2026-08-25 10:48

import django.utils.timezone
from django.db import migrations, models


def backfill_finished_at(apps, schema_editor):
    """Rows created before the device-registration change were written only
    when the whole survey was finished, so they are completions by definition."""
    AnonymousParticipation = apps.get_model('surveys', 'AnonymousParticipation')
    AnonymousParticipation.objects.filter(finished_at__isnull=True).update(
        finished_at=models.F('completed_at')
    )


def unbackfill_finished_at(apps, schema_editor):
    AnonymousParticipation = apps.get_model('surveys', 'AnonymousParticipation')
    AnonymousParticipation.objects.update(finished_at=None)


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0016_enforce_question_answer_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymousparticipation',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان تکمیل'),
        ),
        migrations.RunPython(backfill_finished_at, unbackfill_finished_at),
        migrations.AlterField(
            model_name='anonymousparticipation',
            name='completed_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان ثبت'),
        ),
    ]
