# Generated by Django 5.2.16 on 2026-08-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0018_anonymousparticipation_finished_at_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='surveyperson',
            index=models.Index(fields=['survey', 'is_active'], name='surveyp_survey_active_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyquestion',
            index=models.Index(fields=['survey', 'is_active', 'person', 'display_order'], name='surveyq_active_person_idx'),
        ),
    ]
